<?php
/**
 * @var $block \MagentoEse\InStorePickup\Block\StoreDetails
 */
$storeLocation = $block->getChosenStoreLocation();
?>
<h3>My Local Stores</h3>
<h4><?php echo $storeLocation->getName(); ?> <a href="#" class="cboxElement instorepickup-search-trigger">Change</a></h4>
<address><?php echo $storeLocation->getStreetAddress(); ?><br><?php echo $storeLocation->getCity(); ?>, <?php echo $storeLocation->getState(); ?> <?php echo $storeLocation->getPostalCode(); ?><br><?php echo $storeLocation->getPhone(); ?></address>

<?php /* include static block here */ ?>
<h4>Regular Hours</h4>
<ul>
    <li class="odd">
        <p>Monday</p>
        <span>10:00am to 9:00pm</span>
    </li>
    <li class="even">
        <p>Tuesday</p>
        <span>10:00am to 9:00pm</span>
    </li>
    <li class="odd">
        <p>Wednesday</p>
        <span>10:00am to 9:00pm</span>
    </li>
    <li class="even">
        <p>Thursday</p>
        <span>10:00am to 9:00pm</span>
    </li>
    <li class="odd">
        <p>Saturday</p>
        <span>10:00am to 9:00pm</span>
    </li>

    <li class="even">
        <p>Sunday</p>
        <span>11:00am to 6:00pm</span>
    </li>
</ul>