<?php
/**
 * @var $block \MagentoEse\InStorePickup\Block\StoreSelector
 */
?>

<?php if ($this->helper('MagentoEse\InStorePickup\Helper\Data')->isInStorePickupEnabled()): ?>
    <div class="switcher instorepickup switcher-instorepickup" data-ui-id="instorepickup-switcher" id="switcher-instorepickup" style="display:none!important">

        <div class="actions dropdown options switcher-options">
            <div class="action toggle instorepickup-trigger instorepickup-nav-container instorepickup-search-trigger" id="switcher-instorepickup-trigger">
                <strong>

                    <?php echo $block->getChildHtml('magentoese_instorepickup_nav_label') ?>

                </strong>
            </div>
            <div class="dropdown instorepickup-dropdown"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                    "appendTo":"#switcher-instorepickup > .options",
                    "triggerTarget":"#switcher-instorepickup-trigger",
                    "closeOnMouseLeave": false,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":null}}'>

                <?php echo $block->getChildHtml('magentoese_instorepickup_nav_dropdown') ?>

            </div>
        </div>
    </div>
<?php endif; ?>
