<?php

/** @var $block \MagentoEse\InStorePickup\Block\Product\View\InStorePickup */
?>

<?php if ($this->helper('MagentoEse\InStorePickup\Helper\Data')->isInStorePickupEnabled()): ?>
    <div class="instorepickup-pdp-wrapper">
    <?php if ($block->isAvailableInStore()): ?>
        <?php echo $block->getChildHtml('product.info.instorepickup.options') ?>
    <?php elseif ($block->isOnlineExclusive()): ?>
        <span class="availability-label">
            <?php echo __('Availability') ?>:
            <span class="availability-result"><?php echo $block->getAvailabilityText() ?></span>
        </span>

    <?php endif; ?>
    </div>
<?php endif; ?>
