<?php
/**
 * @var $block \MagentoEse\InStorePickup\Block\StoreSelectorScopePrivate
 */
?>
<?php
/** @var $storeLocation \MagentoEse\InStorePickup\Model\StoreLocation */
$storeLocation = $block->getChosenStoreLocation();
?>
<?php if($block->hasStoreBeenChosen()): ?>
    <span><?php echo __('Availability') ?></span>
    <p><?php echo __('In Store') ?></p>


    <span><?php echo __('My Store') ?>: <?php echo $storeLocation->getName() ?></span>

    <div class="addtocart-mode">
        <ul class="form-list">
            <li class="control selected-radio">
                <input type="radio" class="radio" checked="checked" value="ship-to-home" id="ship-to-home" name="instorepickup_addtocart_method">
                <label for="ship-to-home">Ship to Home</label>
            </li>
            <li class="control">
                <input type="radio" class="radio" value="pick-up" id="pick-up" name="instorepickup_addtocart_method">
                <label for="pick-up">Pick up in your local store<span>Available for pickup <b>TODAY</b></span></label>
            </li>
        </ul>
        <span class="label">
            <label><b><?php echo $storeLocation->getName(); ?></b> <span class="action instorepickup-change-trigger"><?php echo __('Change') ?></span></label>
            <address><?php echo $storeLocation->getStreetAddress(); ?><br><?php echo $storeLocation->getCity(); ?>, <?php echo $storeLocation->getState(); ?> <?php echo $storeLocation->getPostalCode(); ?><br><?php echo $storeLocation->getPhone(); ?></address>
        </span>
    </div>

<?php else: ?>
    <span class="instorepickup-change-trigger"><?php echo __('Check in-store availability') ?></span>
<?php endif; ?>

