<?php
return array (
    ['Green Oak Village Place',27],
    ['Village Arcade',9],
    ['Panama City Mall',18],
    ['Dadeland Mall',10],
    ['Northpark',49],
    ['Santa Rosa',53],
    ['Southern Hills',12],
    ['Santa Anita Fashion Park',8],
    ['Grand Teton',4],
    ['Alderwood',51],
    ['King of Prussia',30],
    ['Crossroads',48],
    ['Hamilton',45],
    ['Nittany Mall',28],
    ['Warwick',4],
    ['Valley Plaza',43],
    ['Hanes Mall',43],
    ['Bay Shore',31],
    ['Lakeside',28],
    ['The Mall at Sierra Vista',49],
    ['Cherry Creek',53],
    ['Cherryvale',11],
    ['Cortana',6],
    ['Parkdale Mall',48],
    ['Oak View',9],
    ['Vintage Faire',9],
    ['Foothills Fashion',16],
    ['Melbourne Square',3],
    ['Dakota Square',21],
    ['Sunrise',40],
    ['The Summit Sierra',33],
    ['Volusia',43],
    ['Manhattan Town',9],
    ['Mall at Stonecrest',23],
    ['Chambersburg',37],
    ['Plaza Camino Real',8],
    ['The Shoppes at Montage',38],
    ['Northfield at Stapleton',2],
    ['Exton Square',7],
    ['Chesapeake Square',28],
    ['Monmouth',11],
    ['Avenue at East Cobb',27],
    ['Mission Viejo',47],
    ['Green Acres',49],
    ['Findlay Village',48],
    ['Bridgehampton Commons',42],
    ['Northgate Mall',13],
    ['Opry Mills',46],
    ['Edgewater',29],
    ['Livingston',10],
    ['Cottonwood',16],
    ['Faneuil Hall Marketplace',49],
    ['Gallatin Valley Mall',36],
    ['Dallas Galleria',34],
    ['MainPlace',7],
    ['Holiday Village',42],
    ['Fashion Square Sherman Oaks',30],
    ['Killeen',22],
    ['The Shops at Norterra',22],
    ['Marlton Square',44],
    ['North Riverside Park',48],
    ['St. Charles Town Center',0],
    ['The Shoppes at Buckland Hills',16],
    ['Susquehanna Valley',29],
    ['Southern Park',41],
    ['Barton Creek Square',12],
    ['Castleton Square',43],
    ['Honey Creek',21],
    ['White Oaks',29],
    ['Valle Vista',28],
    ['Kenwood Towne Centre',0],
    ['University',23],
    ['Stonestown Galleria',8],
    ['The Promenade at Temecula',25],
    ['Acadiana Mall',48],
    ['Charlottesville Fashion Square',5],
    ['Galleria at Tyler',43],
    ['Brookwood Village',38],
    ['Boise Towne Square',6],
    ['Broadway Soho',27],
    ['Great Lakes',8],
    ['Great Northern',14],
    ['Riverchase Galleria',44],
    ['Saint Louis Galleria',19],
    ['Atlantic Station',19],
    ['Greenwood',37],
    ['Firewheel Town Center',19],
    ['Galleria at Roseville',39],
    ['Ford City',31],
    ['Southpark',40],
    ['Quaker Bridge',0],
    ['Madison Square',41],
    ['Premier Center',42],
    ['Northshore',34],
    ['The Mall at Wellington Green',45],
    ['Sarasota Square',18],
    ['Twelve Oaks Mall',6],
    ['Deptford',31],
    ['Somerset Square',29],
    ['Southbridge',1],
    ['Francis Scott Key',25],
    ['Chesterfield Towne',16],
    ['Fashion Square Sherman Oaks',3],
    ['The Galleria at Fort Lauderdale',21],
    ['Bassett',43],
    ['Macarthur',43],
    ['The Esplanade',35],
    ['Bangor',47],
    ['Cielo Vista',21],
    ['Colony Square',19],
    ['Newgate',31],
    ['South County',47],
    ['Westminster Mall',32],
    ['Mall of America',19],
    ['Peru Mall',53],
    ['Shops at Riverwoods',50],
    ['Otay Ranch Town Center',34],
    ['Shadow Lake Towne Center',23],
    ['University Mall',15],
    ['Gateway',4],
    ['Providence Place',30],
    ['Deer Park Town Center',29],
    ['The Pier Shops at Caesars',3],
    ['Westfield Culver City',37],
    ['Cocowalk',13],
    ['Carolina',10],
    ['West Towne',12],
    ['The Citadel',32],
    ['Deptford',13],
    ['Northpark',27],
    ['Mount Berry Square',40],
    ['Solomon Pond',13],
    ['Queens Center Mall',53],
    ['Mission Valley',11],
    ['Flatiron Crossing',3],
    ['Ross Park',38],
    ['Florida Mall',18],
    ['Sikes Senter',32],
    ['Station Park',51],
    ['River Oaks',53],
    ['Orlando Premium Outlets',3],
    ['University',21],
    ['Greenville Mall',42],
    ['Summit',39],
    ['Mall at Greece Ridge',16],
    ['Weberstown',18],
    ['West Oaks',44],
    ['Northwest Arkansas',2],
    ['Mayfair',42],
    ['Santa Rosa',43],
    ['Manhattan Mall',34],
    ['Quincy',43],
    ['Streets at Southpoint',3],
    ['Los Cerritos',50],
    ['River Hills',26],
    ['Shops at Sunset Place',36],
    ['Pittsburgh Mills',46],
    ['Moorestown',15],
    ['Pacific View Ventura',48],
    ['Southlands',30],
    ['Parkway',7],
    ['Monroeville',0],
    ['Cross Creek',32],
    ['Colorado Mills',53],
    ['Franklin Park',9],
    ['Greenbrier',47],
    ['Zona Rosa',46],
    ['Columbia',37],
    ['Rock Hill Galleria',49],
    ['Country Club',24],
    ['Mall St. Vincent',28],
    ['Alamo Quarry Market',14],
    ['Meadowood',43],
    ['Colonial Mall Auburn',10],
    ['Southpark',31],
    ['Central',16],
    ['Orland Square',42],
    ['Riverside Square',1],
    ['Sunvalley',43],
    ['Dover',50],
    ['La Palmera',12],
    ['Burlington Town Center',21],
    ['Oakwood',15],
    ['North County Fair',14],
    ['Chino Hills',23],
    ['Carriage Crossing',20],
    ['Oaks',30],
    ['Galleria at Sunset',40],
    ['Cherry Hill',53],
    ['Southland',40],
    ['Dogwood Festival',42],
    ['Woodbury Plaza',36],
    ['Miami Lakes',1],
    ['Seminole Towne',6],
    ['The Dolphin Mall',27],
    ['Stamford Town',7],
    ['Mall at Steamtown',11],
    ['Tacoma',34],
    ['Gwinnett Place',29],
    ['Plaza Del Sol',43],
    ['Marketstreet at Lynnfield',22],
    ['Main Street',34],
    ['Johnstown Galleria',52],
    ['Knoxville Center',50],
    ['Chico Mall',40],
    ['Mt. Shasta Mall',49],
    ['Oakridge Mall',20],
    ['Park Plaza',7],
    ['Eastern Hills',29],
    ['The Waterfront',16],
    ['Manassas',47],
    ['Baybrook',27],
    ['Solano',46],
    ['Northlake',43],
    ['Cascade Mall',24],
    ['Collin Creek',44],
    ['Kings Plaza Shopping Center',41],
    ['Millcreek',20],
    ['Oakridge',32],
    ['Connecticut Post',47],
    ['Grand Traverse',29],
    ['Perimeter Mall',8],
    ['The Mall at Short Hills',4],
    ['La Encantada',0],
    ['Provo Towne Centre',39],
    ['Pavilion at Turkey Creek',36],
    ['Crossroads',10],
    ['Laurel Park Place',48],
    ['Southern Park',52],
    ['Kitsap',5],
    ['Collins Avenue',34],
    ['Eastland',45],
    ['Augusta Mall',18],
    ['Aviation',8],
    ['Midway Mall',41],
    ['Auburn',20],
    ['Clackamas Town Center',30],
    ['Watters Creek',36],
    ['Golden Triangle',36],
    ['Crestview Hills',20],
    ['Eastgate',48],
    ['The Plaza at West Covina',18],
    ['Clay Terrace',52],
    ['University Towne Center',47],
    ['Avon Marketplace',24],
    ['Simi Valley Town Center',34],
    ['Pierre Bossier',43],
    ['Fashion Square',6],
    ['Palmer Park',9],
    ['Higuera Street',27],
    ['Arbor Lakes Lifestyle Center',3],
    ['Aventura',40],
    ['Mesa Mall',30],
    ['Bellis Fair',31],
    ['Colonie',9],
    ['Vista Ridge',9],
    ['Tippecanoe',18],
    ['Magic Valley',10],
    ['Phillipsburg',50],
    ['Metropolis',5],
    ['Pheasant Lane',38],
    ['Alexandria',13],
    ['The Forum at Carlsbad',6],
    ['Ridgedale Shopping Center',47],
    ['Coastland',53],
    ['Hollywood and Highland',17],
    ['South Mall',35],
    ['The Mall at Rockingham Park',16],
    ['Fashion Fair',31],
    ['Burlington',51],
    ['Franklin Mills',4],
    ['Enfield Square',26],
    ['Arrowhead Towne',10],
    ['Valley West',30],
    ['Towne West Square',10],
    ['Woodland Mall',16],
    ['Winter Garden Village',50],
    ['Victoria Gardens',39],
    ['Tacoma',45],
    ['Spring Hill',3],
    ['Chapel Hills',43],
    ['Beaver Valley',42],
    ['Quail Springs',30],
    ['Maplewood',24],
    ['East Towne',31],
    ['Oakland',31],
    ['Square One',5],
    ['Decatur',43],
    ['Columbia',38],
    ['Southridge',6],
    ['South Shore',25],
    ['South Shore',53],
    ['Apple Blossom',27],
    ['Oxford Valley',32],
    ['Hulen',26],
    ['Southland',33],
    ['Valencia Town',35],
    ['Ross Park',24],
    ['Tempe Marketplace',14],
    ['Superstition Springs',51],
    ['The Shops at Mission Viejo',53],
    ['Shoppes at the Palazzo',2],
    ['Park City',17],
    ['Carolina Place',23],
    ['Broadway Mall',11],
    ['Irving',42],
    ['Orchard Town Center',14],
    ['Stoneridge',51],
    ['Forum on Peachtree Parkway',53],
    ['Westgate Mall',6],
    ['Louis Joliet',32],
    ['Tysons Corner',34],
    ['Sunrise',19],
    ['Southcenter',49],
    ['Granite Run',28],
    ['Gadsden',47],
    ['Valley Mall',42],
    ['Kierland Commons',14],
    ['The Shops at Ithaca Mall',1],
    ['Stanford Shopping Center',17],
    ['Arnot',30],
    ['Christiana',43],
    ['Berkshire Mall',18],
    ['Mid Rivers',14],
    ['Gulf View Square',16],
    ['The Streets of Indian Lake',41],
    ['Stony Point',50],
    ['The Commons at Federal Way',18],
    ['The Falls',50],
    ['Prime Outlets at San Marcos',35],
    ['Sommersville Town Center',24],
    ['Alderwood',18],
    ['Bridge Street',15],
    ['Coronado',23],
    ['Garden State Plaza',16],
    ['Savannah Mall',12],
    ['University',14],
    ['Fort Henry',32],
    ['Independence',12],
    ['Northwoods',19],
    ['Southlake Town Square',7],
    ['Kentucky Oaks',30],
    ['Miller Hill',24],
    ['Apache Mall',30],
    ['Sumter Mall',24],
    ['White Marsh',30],
    ['The Dolphin Mall',23],
    ['Southpark',28],
    ['Mall of America',18],
    ['Everett',6],
    ['Harborplace and The Gallery',28],
    ['Town Square',17],
    ['The Meadows',3],
    ['Crossgates',17],
    ['Fashion Valley',21],
    ['Rolling Oaks',2],
    ['Mall of Louisiana',0],
    ['Santa Fe Place',50],
    ['Fig at 7th',33],
    ['The Parks at Arlington',17],
    ['Bell Tower Shops',41],
    ['Palisades',44],
    ['Northgate',46],
    ['Temple',42],
    ['Powell Street',21],
    ['Sooner Fashion',34],
    ['Sunrise',52],
    ['Aurora',52],
    ['Stones River',51],
    ['Old Orchard',44],
    ['Rimrock',15],
    ['Branson Landing',53],
    ['Four Seasons Town Centre',2],
    ['Fashion Island',12],
    ['Mall of the Bluffs',3],
    ['Chautauqua',33],
    ['Chestnut Hill',50],
    ['Tri-County',41],
    ['Pecanland Mall',1],
    ['North Star Mall',47],
    ['Legacy Place',14],
    ['Century Shopping Centre',37],
    ['Walden Galleria',37],
    ['Mayfair',19],
    ['Great Lakes Crossing',40],
    ['South Hills Village',36],
    ['Washington Square',5],
    ['Arden Fair',28],
    ['Ingram Park',16],
    ['Paradise Valley',52],
    ['Oakdale',51],
    ['Arsenal',46],
    ['West Oaks',21],
    ['West Ridge',20],
    ['Serramonte',41],
    ['Holyoke Mall at Ingleside',38],
    ['River Center',12],
    ['North Grand',1],
    ['Bay Park Square',21],
    ['Algonquin Commons',52],
    ['Arden Fair',35],
    ['Square One',18],
    ['Crossgates Mall',42],
);
